(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(codeium/metadata/api_key "a911f42b-69f1-432f-a030-e23ceee0cc6c")
 '(custom-safe-themes
   '("3fe1ebb870cc8a28e69763dde7b08c0f6b7e71cc310ffc3394622e5df6e4f0da" "8c7e832be864674c220f9a9361c851917a93f921fedb7717b1b5ece47690c098" default))
 '(elfeed-feeds
   '("===Youtube_Linux===" "https://www.youtube.com/feeds/videos.xml?channel_id=UC2eYFnH61tmytImy1mTYvhA" "https://www.youtube.com/feeds/videos.xml?channel_id=UCVls1GmFKf6WlTraIb_IaJg" "https://www.youtube.com/feeds/videos.xml?channel_id=UC7YOGHUfC1Tb6E4pudI9STA" "https://www.youtube.com/feeds/videos.xml?channel_id=UCkK9UDm_ZNrq_rIXCz3xCGA" "https://www.youtube.com/feeds/videos.xml?channel_id=UCld68syR8Wi-GY_n4CaoJGA" "===Youtube_Geopolítica===" "https://www.youtube.com/feeds/videos.xml?channel_id=UCNlCllCWYAtU7TzBNKwaMHw" "===Youtube_Chernobil===" "https://www.youtube.com/feeds/videos.xml?channel_id=UCmrLCXSDScliR7q8AxxjvXg" "https://www.youtube.com/feeds/videos.xml?channel_id=UC-yewGHQbNFpDrGM0diZOLA" "https://www.youtube.com/feeds/videos.xml?channel_id=UC0aanx5rpr7D1M7KCFYzrLQ" "https://www.youtube.com/feeds/videos.xml?channel_id=UCyR3jMVUgZadX9dHjuKFuMQ" "===Youtube_Política_e_Filosofia===" "https://www.youtube.com/feeds/videos.xml?channel_id=UCcoxGCRGcq6FhHbEvr2y9Vg" "https://www.youtube.com/feeds/videos.xml?channel_id=UC7-Pp09PJX_SYP9oyMzUAtg" "https://www.youtube.com/feeds/videos.xml?channel_id=UCrx2zrPjhGRi9TwszZiLwEg" "https://www.youtube.com/feeds/videos.xml?channel_id=UCR6LasBpceuYUhuLToKBzvQ" "===Youtube_Misc===" "https://www.youtube.com/feeds/videos.xml?channel_id=UCKaoE6fyoUJOgcoqbyuK9LQ" "===Youtube_Games===" "https://www.youtube.com/feeds/videos.xml?channel_id=UCD6VugMZKRhSyzWEWA9W2fg" "===Podcasts===" "https://feeds.feedburner.com/XadrezVerbal" "===Youtube_Investimentos===" "https://www.youtube.com/feeds/videos.xml?channel_id=UCsra3f6ogpXhIZbSUe2OoaA" "===Random_Websites===" "https://hnrss.org/best" "https://longreads.com/feed/" "https://www.foreignaffairs.com/rss.xml" "https://www.wired.com/feed/rss" "===Blogs===" "https://lukesmith.xyz/index.xml" "===Lemmy===" "https://lemmygrad.ml/feeds/local.xml?sort=Active" "https://lemmy.ml/feeds/local.xml?sort=Active" "===Reddit===" "https://www.reddit.com/r/archlinux/top/.rss?limit=20" "https://www.reddit.com/r/voidlinux/top/.rss?limit=20" "https://www.reddit.com/r/linux/top/.rss?limit=20" "https://www.reddit.com/r/obsidianmd/top/.rss?limit=20" "https://www.reddit.com/r/indepthstories/top/.rss?limit=20" "https://www.reddit.com/r/wallstreetbets/top/.rss?limit=20" "https://www.reddit.com/r/investimentos/top/.rss?limit=20" "===Void===" "https://github.com/void-linux/void-packages/commits/master.atom" "===Github===" "https://github.com/qutebrowser/qutebrowser/releases.atom" "https://github.com/ihabunek/toot/releases.atom" "https://github.com/neovim/neovim/releases.atom" "===Steam===" "https://store.steampowered.com/feeds/newreleases.xml" "https://steamcommunity.com/games/975370/rss/" "===Peertube===" "https://jupiter.tube/feeds/videos.xml?sort=-publishedAt&isLocal=true" "https://videos.lukesmith.xyz/feeds/videos.xml?sort=-publishedAt&isLocal=true" "https://comics.peertube.biz/feeds/videos.xml?sort=-publishedAt&isLocal=true"))
 '(magit-todos-insert-after '(bottom) nil nil "Changed by setter of obsolete option `magit-todos-insert-at'"))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
